"""add data_exame to exames_imagem

Revision ID: 3f6734c35214
Revises: 9a434e1dda06
Create Date: 2025-06-03 02:03:43.116566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f6734c35214'
down_revision = '9a434e1dda06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exame_imagem_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'exames_imagem', ['exame_imagem_id'], ['id'])

    with op.batch_alter_table('exames_imagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_exame', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('medico_solicitante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('orthanc_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shosp_agendamento_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prestador_codigo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('prestador_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_especial', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('link_gravacao', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('senha_gravacao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('observacoes_gravacao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('exame_principal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_complemento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('assistente_id', sa.Integer(), nullable=True))
        batch_op.alter_column('data_realizacao',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pendente_laudo', 'laudo_disponivel'),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('orthanc_study_uid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['orthanc_study_uid'])
        batch_op.drop_constraint(batch_op.f('exames_imagem_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['assistente_id'], ['id'])
        batch_op.create_foreign_key(None, 'exames_imagem', ['exame_principal_id'], ['id'])
        batch_op.drop_column('laudo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exames_imagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laudo_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exames_imagem_ibfk_2'), 'documentos', ['laudo_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('orthanc_study_uid',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('pendente_laudo', 'laudo_disponivel'),
               nullable=True)
        batch_op.alter_column('data_realizacao',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('assistente_id')
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('observacoes_complemento')
        batch_op.drop_column('exame_principal_id')
        batch_op.drop_column('observacoes_gravacao')
        batch_op.drop_column('senha_gravacao')
        batch_op.drop_column('link_gravacao')
        batch_op.drop_column('tipo_especial')
        batch_op.drop_column('prestador_nome')
        batch_op.drop_column('prestador_codigo')
        batch_op.drop_column('shosp_agendamento_id')
        batch_op.drop_column('orthanc_id')
        batch_op.drop_column('medico_solicitante')
        batch_op.drop_column('data_exame')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exame_imagem_id')

    # ### end Alembic commands ###
