"""Migração inicial

Revision ID: 9a434e1dda06
Revises: 
Create Date: 2025-05-31 13:55:32.678197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a434e1dda06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_perfil', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuario_perfil_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuario_perfil_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'perfis', ['perfil_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)

    with op.batch_alter_table('usuario_perfil', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuario_perfil_ibfk_2'), 'perfis', ['perfil_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('usuario_perfil_ibfk_1'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
